//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int RarityId { get; set; }
        public int HeroClassId { get; set; }
        public double Price { get; set; }
    
        public virtual HeroClass HeroClass { get; set; }
        public virtual Rarity Rarity { get; set; }
    }
}
